import = [
  "~/.config/alacritty/tokyonight_night.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[window]
padding = {x=5 , y=5}
decorations="None"
opacity=0.8
blur=true

[selection]
save_to_clipboard=true

[cursor]
style={shape="Underline",blinking="On"}
blink_timeout=0

[keyboard]
bindings = [
   { key = "Return", mods = "Alt|Shift", action = "SpawnNewInstance" }
]

